apiVersion: v1
kind: Pod
metadata:
  name: angular-web
  labels:
    app: static-web
spec:
  containers:
    - name: angular-project-1
      image: hemanthdasharath/angular-web-app
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: static-web-service
spec:
  type: NodePort
  selector:
    app: static-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # Exposes on localhost:30080

