apiVersion: v1
kind: Service
metadata:
  name: angular-web-service
spec:
  type: NodePort
  selector:
    app: angular-web
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # You will access http://<minikube-ip>:30080
